# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sin_wave.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/sin_wave.proto\"p\n\x05\x42\x61tch\x12\x1c\n\x05items\x18\x01 \x03(\x0b\x32\r.Batch.Sample\x1aI\n\x06Sample\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x11\n\tfrequency\x18\x03 \x01(\r\x12\x0c\n\x04time\x18\x04 \x01(\x01\x12\r\n\x05value\x18\x05 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sin_wave_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BATCH']._serialized_start=24
  _globals['_BATCH']._serialized_end=136
  _globals['_BATCH_SAMPLE']._serialized_start=63
  _globals['_BATCH_SAMPLE']._serialized_end=136
# @@protoc_insertion_point(module_scope)
